### PR TITLE
Document how to perform a release.

### PR DESCRIPTION
**Pull request by markpatton**
See https://github.com/eclipse-pass/main/blob/196-release/docs/dev/release.md

This is a rough draft. Still some formatting to do. Is the level of detail right?

### CODE REVIEW

**Review by bbranan — COMMENTED** [review]
This is a good overview of the release process as it stands today, which is the right place to start. The level of detail seems appropriate. As a guiding principle, any PASS committer should be able to walk through the steps in this document and perform a release.

The ordering of the doc should reflect the steps as they need to happen, so you may want to move the maven settings setup to a release preparation section nearer to the top. I can see also wanting to specify things like Java version, Maven version, etc, so that's all clear.

I'd like to see something in this doc about a GitHub release. I can see wanting to include Release Notes in the GitHub release and include a link to all releases in the `main` project documentation (or vise versa).

Consider adding a pre-release section for community activities surrounding release which we can expand on later. A few examples (adapted a bit from the DuraCloud release process):
* Assign a Release Manager, the person who will be responsible for the release process. The Release Manager must be a PASS committer.
* Ensure all code commits and PRs intended for the release have been merged.
* Issue a code freeze statement on the Eclipse PASS slack #general channel to notify all developers that a release is imminent and that no further changes will be considered.

You may also want to add a post-release section where you could include notes about things like:
* updating release notes
* updating project documentation based on changes in the release
* deploying the release

It's not necessary for these pre/post sections to be fully fleshed out, but having a starting point makes it easier to include further updates down the road.

As a note, I believe it's possible to specify all maven projects in the parent pom and let maven handle ordering. We really need to get away from having to manually determine a release order. We also want to get away from manually stepping through and releasing each project independently. That said, capturing the current process as-is makes sense for this doc.

**Comment by markpatton** [comment]
@bbranan You can specify all the maven modules in the parent pom and use the maven reactor for dependencies. But it has a lot of implications. See https://docs.google.com/document/d/1Sg4vkFy7fetMGfCrCprRJF8Y1k4RIQGFevgPidbvdIs/edit?usp=sharing, the Assembling a Super Module section.

**Comment by bbranan** [comment]
@markpatton handling the release via a script rather than utilizing the maven reactor may indeed be easier to set up and use. My primary interest is in having the release process automated so that it is consistent, easily repeatable, and low effort. There are some details we'll need to iron out when considering the scripted approach. For example, I'm assuming the release scripts would be run via GitHub Actions, but this could either be a single Action executed within the main repo or an Action in each repo that is called by an Action in the main repo (which is acting more as an orchestrator).

**Comment by markpatton** [comment]
@bbranan Yes. My thought was to automate at least the Java projects with a script instead of the super pom. Both approaches have pluses and minuses. I'm not to tied to which way we go, but I think it should be done as part of another issue.

This GitHub document tries to document how releases currently work given our existing constraints and practices. Once we add some nice automation it can be updated.

**Review by bbranan — APPROVED** [review]
Agreed, this is a good start. I'm in favor of merging these docs and exploring automation in a new ticket.

**Review by jrmartino — COMMENTED** [review]
this looks great - one question -  looking at the java section, are we doing anything with fcrepo regarding releases?

**Comment by markpatton** [comment]
@jrmartino For fcrepo, that's covered in the Docker image release section. But it would probably be good to add some more details. That you have to edit the Dockerfile for pass-authz.

**Pull request merged**
