### PR TITLE
Update documentation to reflect new release

### PR DESCRIPTION
**Pull request by markpatton**
Added a new page with a description of the new architecture and some of the reasoning about tech choices.

This could instead be integrated into the main infra.md/README.md if that makes more sense.

### CODE REVIEW

**Comment by bbranan** [comment]
This is good information, my primary question is how to organize it so that it continues to make sense 6 months or a year from now. We probably don't want a "new architecture" page, for instance, because after even a short period of time the term "new" loses its meaning.

The parts of this describing what changes have been made may fit better in the release notes for the 0.2.0 release. We currently have a release notes document, so that would need to be created. For 0.1.0, the release notes were captured here: https://github.com/eclipse-pass/main/releases/tag/release-v0.1.0. It may be better to capture release notes in a doc that is referenced from the GitHub Release, to keep everything together and maintain a history of changes. When writing release notes, it's important to focus on what actually changed in this specific release.

The notes around architectural goals probably fit best into the infra/README doc.

Some of the forward-looking comments may fit better in the project roadmap doc (under appropriate headers). This is a doc we should probably revisit anyway.

**Comment by markpatton** [comment]
There are release notes for 0.2.0 in docs/dev/CHANGELOG.md which look pretty good.

That would leave updating docs/roadmap.md and docs/infra.md. The roadmap looks easy enough to update.
The infra document is a mix old information, speculation, and details of the jhu deployment. I'm not quite sure how to sensibly update it, but I will give it a try.

**Comment by markpatton** [comment]
As was as doc/dev/CHANGELOG.md there are also notes here: https://github.com/eclipse-pass/main/releases/tag/v0.2.0
This seems redundant. Perhaps the release should link to the changelog?

**Comment by markpatton** [comment]
For completeness here was the original text which does some have some explanation of architecture changes.

# New architecture

PASS is the process of transitioning to a new architecture. Some core technologies are changing. The code is also being reorganized.

Major goals:
  * Simplify the project architecture
  * Reduce dependencies and integration points
  * Define a single, complete PASS API endpoint
  * Ensure the architecture is easily understandable, deployable, and supportable by Eclipse and other potential hosts
  * Ensure the architecture, project structure, and API are easily understandable, usable, and maintainable by the JHU project team and partner institutions
  * Simplify the release process

The key technology change is the move from using a combination of the Fedora repository and Elasticsearch for managing objects in the PASS data model to Elide.
[Elide](https://elide.io) is a Spring Boot based framework which provides a [JSON:API](https://jsonapi.org/) interface to a Java model along with filtering based on RSQL.
Given the appropriate mostly JPA annotations, the PASS data model was made available without much difficulty. Elide can use a database as a data store or just memory.
The flexibility is convenient for switching between testing and production environments.

The move to Elide drastically reduces the amount of code needed to support the PASS data model and is much easier to manage.
There is no longer a need to maintain a custom adapter for our Ember based pass-ui to interact with Fedora. Ember directly supports JSON:API. Elasticsearch and
the pass-indexer component which sends Fedora objects to Elasticsearch are no longer needed. Some operations which had poor performance like retrieving
all objects of a type from Fedora directly become trivial.

The backend Java code is being consolidated into fewer repositories. Instead of every REST service having a separate repository and Docker image, there is a single repository and Docker image, pass-core,
for the entire REST API. (The Elide JSON:API endpoint lives in this repository.) This drastically reduces the number of repositories and Docker images which need to be managed.
Some of the REST services were originally written in Go, but are now being ported to Java and put in pass-core. Deploying the PASS REST API becomes far easier.

Other backend code like the deposit services, notification services, and the various data loaders will be consolidated into a different reposi

**Comment by bbranan** [comment]
@markpatton:
- The changes to the README look fine to me, but I'd want @jrmartino or @jabrah to validate that the final list captures the full set of current build artifacts
- The roadmap list for 0.3.0 could also include: new file service (with support for both local and S3 storage), replacement of all Golang services. Won't there be a need for additional auth work in the UI, especially if access control is added to the REST API?
- Consider expanding the release 0.2.0 entry in the changelog to include some of the additional detail that you wrote up in the original New Architecture doc. The original idea for this was to capture the reasoning behind why we made the move away from Fedora to the new architecture. Capturing some of that thinking in the changelog entry would be valuable.
- I agree that it's duplicative to have the same text in both the changelog doc and in the github release. It would be easy for those to get out of sync. We should decide which of the two is the primary source and link to that source from the other places.

**Review by jrmartino — COMMENTED** [review]
looks good, complete and concise. 

spelling error, line 26, roadmap - "frameword" :-)

**Pull request merged**
