### PR TITLE
Troubleshooting Doc For Pass-core in Docker on Windows

### PR DESCRIPTION
**Pull request by tsande16**
There is a known issue with line breaks using Docker on a Windows machine. This is the simplest work-around that I can find. It is recommended from the git documentation that Windows developers use `core.autocrlf=true` in their `gitconfig` when working a mixed environment development team. Using this configuration will make clones/checkouts with windows style line endings and commits with unix/linux line endings. This will still cause the error when running docker on windows. There is an option to set `core.autocrlf=input` which would make clones/checkouts unix/linux and commits unix/linux. I'm not sure of any issues with doing this on a windows machine and so far the simplest solution has been to just modify the two files mentioned in the documentation. Also, for the community this is the quickest solution for them to get pass-core up and running.

[core.autocrlf true](https://git-scm.com/book/en/v2/Customizing-Git-Git-Configuration#_formatting_and_whitespace)

### CODE REVIEW

**Review by jabrah — COMMENTED** [review]
Does this cause git to pick up the files? We shouldn't commit the changed files with windows line endings, though git should automatically commit with unix line endings so maybe it's not an issue

**Comment by tsande16** [comment]
From my understanding with this setting in the global git config: `core.autocrlf=true`, Windows endings will be converted to Unix/Linux. I originally didn't have this set prior to yesterday, so one way to test is if the File Service files have unix/linux or windows endings. I think by default git on Windows doesn't automatically convert because I had to manually convert these files when I cloned pass-core; however new files might be different? What do you see with the 305-File-Service in pass-core?

**Comment by tsande16** [comment]
Just some more information: reading through the documentation and testing, it seems like the default install for git on windows will have core.autocrlf=true for the system wide git config. There are 2 other types on git config: global and local. Both global and local do not have this setting configured, but it is true for the system setting.

**Comment by tsande16** [comment]
So what will happen if someone tries to change the line endings from CRLF (windows) to LF (unix/linux) on a default windows git setup it will fail to commit the files. Changing them back to CRLF from LF will also fail to commit. So for a default windows git configuration, it should be protected from messing up the line endings in the remote.

**Comment by jabrah** [comment]
Cool. I think we should make a note of that in the docs

**Comment by markpatton** [comment]
I'm a little confused. The text implies that in pass-core-main entrypoint.sh and init_postgres.sh have windows line endings. But when I download the raw files from github (trying to avoid any translation), they seem to have unix file endings. Am I missing something?

And if the issue is that those two files  were somehow committed with windows line endings, can we just fix those two files?

**Comment by markpatton** [comment]
Ok. I think I see. When git is checking things out on windows, the windows line endings are added to the .sh files. Then those files are used by the docker image which runs linux and expects unix line endings.

**Comment by tsande16** [comment]
On a Windows default Git configuration it will checkout with Windows style line endings. These two files need to have LF line endings in order for docker to run properly. The title implies this happens on Windows machines. If there was someone in the community that cloned this and tried to run it locally in docker, it wouldn't run properly using default configurations of Git. They would have to change their git configuration to checkout files with Linux style endings, which would be unusual for someone developing on a Windows machine. I'm hoping this documentation would help Windows users to be aware of this issue.

These files weren't commited with windows style endings: 
"On a Windows OS, the default Git system configuration clones/checkouts files with CRLF line breaks and will commit files 
with LF line breaks."

**Comment by tsande16** [comment]
From our scrum meeting this morning. Documentation will not be captured in the troubleshooting documentation and the documentation should be captured #408

**Pull request closed without merging**
